//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowPages.Utils.Inputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileDetailInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileDetailInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecflowPages.Utils.Inputs.ProfileDetailInput", typeof(ProfileDetailInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[3]/form/div[5]/div[1]/div[2]/div/table/thead/tr/th[4]/div.
        /// </summary>
        internal static string addCertificationToAdd {
            get {
                return ResourceManager.GetString("addCertificationToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[3]/form/div[4]/div/div[2]/div/table/thead/tr/th[6]/div.
        /// </summary>
        internal static string addEducationToAdd {
            get {
                return ResourceManager.GetString("addEducationToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[3]/form/div[5]/div[1]/div[2]/div/div/div[3]/input[1].
        /// </summary>
        internal static string addFilledCertificationDetails {
            get {
                return ResourceManager.GetString("addFilledCertificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;account-profile-section&quot;]/div/section[2]/div/div/div/div[3]/form/div[4]/div/div[2]/div/div/div[3]/div/input[1].
        /// </summary>
        internal static string addFilledEducation {
            get {
                return ResourceManager.GetString("addFilledEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;buttons-wrapper&apos;]//input[@class=&apos;ui teal button &apos;].
        /// </summary>
        internal static string addFilledSkill {
            get {
                return ResourceManager.GetString("addFilledSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui teal button&apos;].
        /// </summary>
        internal static string addNewEducation {
            get {
                return ResourceManager.GetString("addNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui teal button&apos;].
        /// </summary>
        internal static string addNewSkill {
            get {
                return ResourceManager.GetString("addNewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;account-profile-section&quot;]/div/section[2]/div/div/div/div[3]/form/div[3]/div/div[2]/div/table/thead/tr/th[3]/div.
        /// </summary>
        internal static string addNewSkillsToAdd {
            get {
                return ResourceManager.GetString("addNewSkillsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;name&apos;][@type=&apos;text&apos;].
        /// </summary>
        internal static string addSkillField {
            get {
                return ResourceManager.GetString("addSkillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium Web driver.
        /// </summary>
        internal static string addSkillValue {
            get {
                return ResourceManager.GetString("addSkillValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[2]/div/span/select.
        /// </summary>
        internal static string availabilityDropDown {
            get {
                return ResourceManager.GetString("availabilityDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Time.
        /// </summary>
        internal static string availabilityFullTime {
            get {
                return ResourceManager.GetString("availabilityFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 30hours a week.
        /// </summary>
        internal static string availabilityHour1 {
            get {
                return ResourceManager.GetString("availabilityHour1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 30hours a week.
        /// </summary>
        internal static string availabilityHour2 {
            get {
                return ResourceManager.GetString("availabilityHour2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As needed.
        /// </summary>
        internal static string availabilityHour3 {
            get {
                return ResourceManager.GetString("availabilityHour3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[3]/div/span/select.
        /// </summary>
        internal static string availabilityHourDD {
            get {
                return ResourceManager.GetString("availabilityHourDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[2]/div/span/i.
        /// </summary>
        internal static string availabilityLink {
            get {
                return ResourceManager.GetString("availabilityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Time.
        /// </summary>
        internal static string availabilityPartTime {
            get {
                return ResourceManager.GetString("availabilityPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;Cancel&apos;][@class=&apos;ui button&apos;].
        /// </summary>
        internal static string cancelEducation {
            get {
                return ResourceManager.GetString("cancelEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;ui button&apos;][@value=&apos;Cancel&apos;].
        /// </summary>
        internal static string cancelSkill {
            get {
                return ResourceManager.GetString("cancelSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@class=&apos;certification-award capitalize&apos;].
        /// </summary>
        internal static string certificateField {
            get {
                return ResourceManager.GetString("certificateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISTQB.
        /// </summary>
        internal static string certificateFieldValue {
            get {
                return ResourceManager.GetString("certificateFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@class=&apos;received-from capitalize&apos;].
        /// </summary>
        internal static string certificateFrom {
            get {
                return ResourceManager.GetString("certificateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISTQB.
        /// </summary>
        internal static string certificateFromValue {
            get {
                return ResourceManager.GetString("certificateFromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui top attached tabular menu&apos;]/a[@data-tab=&apos;fourth&apos;].
        /// </summary>
        internal static string certificationTab {
            get {
                return ResourceManager.GetString("certificationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;certificationYear&apos;][@class=&apos;ui fluid dropdown&apos;].
        /// </summary>
        internal static string certificationYear {
            get {
                return ResourceManager.GetString("certificationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017.
        /// </summary>
        internal static string certifiedInYear {
            get {
                return ResourceManager.GetString("certifiedInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@class=&apos;ui fluid dropdown&apos;][@name=&apos;level&apos;].
        /// </summary>
        internal static string chooseSkillDropdown {
            get {
                return ResourceManager.GetString("chooseSkillDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string chooseSkillValue1 {
            get {
                return ResourceManager.GetString("chooseSkillValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        internal static string chooseSkillValue2 {
            get {
                return ResourceManager.GetString("chooseSkillValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string chooseSkillValue3 {
            get {
                return ResourceManager.GetString("chooseSkillValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@name=&apos;instituteName&apos;].
        /// </summary>
        internal static string collegeName {
            get {
                return ResourceManager.GetString("collegeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIT.
        /// </summary>
        internal static string collegeNameValue {
            get {
                return ResourceManager.GetString("collegeNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string countryCollegeValue {
            get {
                return ResourceManager.GetString("countryCollegeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@class=&apos;ui dropdown&apos;][@name=&apos;country&apos;].
        /// </summary>
        internal static string countryofCollege {
            get {
                return ResourceManager.GetString("countryofCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@name=&apos;degree&apos;].
        /// </summary>
        internal static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Science.
        /// </summary>
        internal static string degreeValue {
            get {
                return ResourceManager.GetString("degreeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;field  &apos;]/textarea.
        /// </summary>
        internal static string descriptionField {
            get {
                return ResourceManager.GetString("descriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h3[@class=&apos;ui dividing header&apos;]/span.
        /// </summary>
        internal static string descriptionIcon {
            get {
                return ResourceManager.GetString("descriptionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;ui teal button&apos;][@type=&apos;button&apos;].
        /// </summary>
        internal static string descriptionSave {
            get {
                return ResourceManager.GetString("descriptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a Test Analyst with good knowledge of Selenium Web Driver and C sharp.
        /// </summary>
        internal static string descriptionValue {
            get {
                return ResourceManager.GetString("descriptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[4]/div/span/select.
        /// </summary>
        internal static string earnTargetDD {
            get {
                return ResourceManager.GetString("earnTargetDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[4]/div/span/i.
        /// </summary>
        internal static string earnTargetLink {
            get {
                return ResourceManager.GetString("earnTargetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than $500 per month.
        /// </summary>
        internal static string earnTargetVal1 {
            get {
                return ResourceManager.GetString("earnTargetVal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between $500 and $1000 per month.
        /// </summary>
        internal static string earnTargetVal2 {
            get {
                return ResourceManager.GetString("earnTargetVal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than $1000 per month.
        /// </summary>
        internal static string earnTargetVal3 {
            get {
                return ResourceManager.GetString("earnTargetVal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui top attached tabular menu&apos;]/a[@data-tab=&apos;third&apos;].
        /// </summary>
        internal static string educationTab {
            get {
                return ResourceManager.GetString("educationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div[3]/div/span/i.
        /// </summary>
        internal static string hoursLink {
            get {
                return ResourceManager.GetString("hoursLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui eight item menu&apos;]/a[contains(@href,&apos;/Account/Profile&apos;)].
        /// </summary>
        internal static string profileTab {
            get {
                return ResourceManager.GetString("profileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;account-profile-section&apos;]/div/section[2]/div/div/div/div[3]/form/div[3]/div/div[2]/div/table/tbody[1]/tr/td[1].
        /// </summary>
        internal static string savedSkillPath {
            get {
                return ResourceManager.GetString("savedSkillPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui top attached tabular menu&apos;]/a[@data-tab=&apos;second&apos;].
        /// </summary>
        internal static string skillTab {
            get {
                return ResourceManager.GetString("skillTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@class=&apos;ui dropdown&apos;][@name=&apos;title&apos;].
        /// </summary>
        internal static string titile {
            get {
                return ResourceManager.GetString("titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.Tech.
        /// </summary>
        internal static string titleValue {
            get {
                return ResourceManager.GetString("titleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@class=&apos;ui dropdown&apos;][@name=&apos;yearOfGraduation&apos;].
        /// </summary>
        internal static string yearOfGrad {
            get {
                return ResourceManager.GetString("yearOfGrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        internal static string yearofGradValue {
            get {
                return ResourceManager.GetString("yearofGradValue", resourceCulture);
            }
        }
    }
}
