//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowPages.Utils.Inputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecondUserInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecondUserInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecflowPages.Utils.Inputs.SecondUserInput", typeof(SecondUserInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@name=&apos;email&apos;].
        /// </summary>
        internal static string emailId {
            get {
                return ResourceManager.GetString("emailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;fluid ui teal button&apos;].
        /// </summary>
        internal static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priyanka18.aus@gmail.com.
        /// </summary>
        internal static string mailID {
            get {
                return ResourceManager.GetString("mailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;password&apos;][@name=&apos;password&apos;].
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prinks01.
        /// </summary>
        internal static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;checkbox&apos;][@name=&apos;rememberDetails&apos;].
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //i[@class=&apos;search link icon&apos;].
        /// </summary>
        internal static string searchIcon {
            get {
                return ResourceManager.GetString("searchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@placeholder=&apos;Search skills&apos;].
        /// </summary>
        internal static string searchSkills {
            get {
                return ResourceManager.GetString("searchSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium Web driver.
        /// </summary>
        internal static string searchValue {
            get {
                return ResourceManager.GetString("searchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;seller-info&apos;][contains(@href,&apos;/Account/Profile?id=5c621663bea4490005ebe9d2&apos;)].
        /// </summary>
        internal static string sellerInfo {
            get {
                return ResourceManager.GetString("sellerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;service-info&apos;][contains(@href,&apos;/Home/ServiceDetail?id=5caab0c0d67ea40005a35146&apos;)].
        /// </summary>
        internal static string serviceInfo {
            get {
                return ResourceManager.GetString("serviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;home&quot;]/div/div/div[1]/div/a.
        /// </summary>
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.skillswap.pro/Home.
        /// </summary>
        internal static string urlPath {
            get {
                return ResourceManager.GetString("urlPath", resourceCulture);
            }
        }
    }
}
