//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowPages.Utils.Inputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkillsInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkillsInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecflowPages.Utils.Inputs.SkillsInput", typeof(SkillsInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string creditValue {
            get {
                return ResourceManager.GetString("creditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I provide selenium web driver training using c sharp language..
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01062019.
        /// </summary>
        internal static string endDateValue {
            get {
                return ResourceManager.GetString("endDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0430PM.
        /// </summary>
        internal static string monEndTime {
            get {
                return ResourceManager.GetString("monEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1005AM.
        /// </summary>
        internal static string monStartTime {
            get {
                return ResourceManager.GetString("monStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java.
        /// </summary>
        internal static string skillExValue {
            get {
                return ResourceManager.GetString("skillExValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming &amp; Tech.
        /// </summary>
        internal static string ssDropdown1Value {
            get {
                return ResourceManager.GetString("ssDropdown1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        internal static string ssDropdown2IValue {
            get {
                return ResourceManager.GetString("ssDropdown2IValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11042019.
        /// </summary>
        internal static string startDateValue {
            get {
                return ResourceManager.GetString("startDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium.
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium Web driver Trainer.
        /// </summary>
        internal static string titleText {
            get {
                return ResourceManager.GetString("titleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Users\\hp\\Desktop\\Test.txt.
        /// </summary>
        internal static string uplaodFilePath {
            get {
                return ResourceManager.GetString("uplaodFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0510PM.
        /// </summary>
        internal static string wedEndTime {
            get {
                return ResourceManager.GetString("wedEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0945AM.
        /// </summary>
        internal static string wedStartTime {
            get {
                return ResourceManager.GetString("wedStartTime", resourceCulture);
            }
        }
    }
}
