//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowPages.Utils.Inputs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XPathInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XPathInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecflowPages.Utils.Inputs.XPathInput", typeof(XPathInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;isActive&apos;][@value=&apos;true&apos;].
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui checkbox&apos;]//input[@index=&apos;1&apos;].
        /// </summary>
        internal static string checkBoxMon {
            get {
                return ResourceManager.GetString("checkBoxMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;ui checkbox&apos;]//input[@index=&apos;3&apos;].
        /// </summary>
        internal static string checkBoxWed {
            get {
                return ResourceManager.GetString("checkBoxWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[8]/div[4]/div/div/input.
        /// </summary>
        internal static string creditField {
            get {
                return ResourceManager.GetString("creditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@name=&apos;description&apos;].
        /// </summary>
        internal static string descriptionField {
            get {
                return ResourceManager.GetString("descriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div/div/div[1]/div/div[1]/div.
        /// </summary>
        internal static string emailField {
            get {
                return ResourceManager.GetString("emailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[7]/div[2]/div/div[1]/div[4]/input.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;EndTime&apos;][@index=&apos;1&apos;].
        /// </summary>
        internal static string endTimeMon {
            get {
                return ResourceManager.GetString("endTimeMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;EndTime&apos;][@index=&apos;3&apos;].
        /// </summary>
        internal static string endTimeWed {
            get {
                return ResourceManager.GetString("endTimeWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;isActive&apos;][@value=&apos;false&apos;].
        /// </summary>
        internal static string hidden {
            get {
                return ResourceManager.GetString("hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;locationType&apos;][@value=&apos;1&apos;].
        /// </summary>
        internal static string locationOnline {
            get {
                return ResourceManager.GetString("locationOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[6]/div[2]/div/div[1]/div/input.
        /// </summary>
        internal static string locationOnsite {
            get {
                return ResourceManager.GetString("locationOnsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;Save&apos;][@type=&apos;button&apos;].
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;serviceType&apos;][@value=&apos;0&apos;].
        /// </summary>
        internal static string serviceHourlyBasis {
            get {
                return ResourceManager.GetString("serviceHourlyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;serviceType&apos;][@value=&apos;1&apos;].
        /// </summary>
        internal static string serviceOneOff {
            get {
                return ResourceManager.GetString("serviceOneOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;right item&apos;]//*[text()=&apos;Share Skill&apos;].
        /// </summary>
        internal static string shareSkillLink {
            get {
                return ResourceManager.GetString("shareSkillLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;right item&apos;]//*[text()=&apos;Share Skill&apos;].
        /// </summary>
        internal static string shareSkillLink1 {
            get {
                return ResourceManager.GetString("shareSkillLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;skillTrades&apos;][@value=&apos;true&apos;].
        /// </summary>
        internal static string skillexRadBtn1 {
            get {
                return ResourceManager.GetString("skillexRadBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name= &apos;skillTrades&apos;][@value=&apos;false&apos;].
        /// </summary>
        internal static string skillexRadBtn2 {
            get {
                return ResourceManager.GetString("skillexRadBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[8]/div[4]/div/div/div/div/div/input.
        /// </summary>
        internal static string skillExText {
            get {
                return ResourceManager.GetString("skillExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;categoryId&apos;][@class=&apos;ui fluid dropdown&apos;].
        /// </summary>
        internal static string ssDropdown1 {
            get {
                return ResourceManager.GetString("ssDropdown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;subcategoryId&apos;][@class=&apos;ui fluid dropdown&apos;].
        /// </summary>
        internal static string ssDropdown2 {
            get {
                return ResourceManager.GetString("ssDropdown2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[7]/div[2]/div/div[1]/div[2]/input.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;StartTime&apos;][@index=&apos;1&apos;].
        /// </summary>
        internal static string startTimeMon {
            get {
                return ResourceManager.GetString("startTimeMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;StartTime&apos;][@index=&apos;3&apos;].
        /// </summary>
        internal static string startTimeWed {
            get {
                return ResourceManager.GetString("startTimeWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;ReactTags__tagInputField&apos;][@type=&apos;text&apos;].
        /// </summary>
        internal static string tagsField {
            get {
                return ResourceManager.GetString("tagsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;text&apos;][@name=&apos;title&apos;].
        /// </summary>
        internal static string titileField {
            get {
                return ResourceManager.GetString("titileField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;service-listing-section&apos;]/div[2]/div/form/div[9]/div/div[2]/section/div/label/div/span/i.
        /// </summary>
        internal static string uploadButton {
            get {
                return ResourceManager.GetString("uploadButton", resourceCulture);
            }
        }
    }
}
